### ISSUE TITLE
Projections and tiled images threshold

### ISSUE THREAD

**Issue by ppouchin** [ome/omero-iviewer#341]
I'm only now seeing that projections are not available for some images because of this PR: https://github.com/ome/omero-iviewer/pull/202
Is there a specific reason to set the threshold for tiled images at [4000000](https://github.com/ome/omero-iviewer/blob/master/src/viewers/viewer/globals.js#L111) (multiple of 1000) instead of 4194304 (multiple of 1024)? 

2048x2048 images are excluded although they're quite common (I think)...

I guess people can always ask for a slightly higher threshold, but I'm under the impression that images often have resolutions based on powers of 2, and the closest threshold for 2000 would be 2048, which is close, where as bigger images with a "standard" resolution would surely be at least 2560 (if not 3072 or 4096), which is considerably larger.

**Comment by will-moore** [comment]
Thanks for pointing that out.
The original use of that threshold was *only* for tiled loading and it was a bit arbitrary since it didn't make that much difference to users if the viewer was loading tiles or whole planes. The server threshold for tiling is about 3k x 3k and the server also won't do projections on tiled images, but it will for 2048x2048.

I'm happy to boost the iviewer threshold above 2048x2048, possibly aligning it with the server's tiles threshold.
However, you should also be aware that the server and iviewer have a projection-specific threshold based on the size of the image (X, Y, Z, C and pixel-type). See https://github.com/ome/omero-web/pull/115 and https://github.com/ome/omero-iviewer/pull/305.
If you have an up-to-date omero-web, can you do max intensity projections in the 'old viewer'?

**Comment by ppouchin** [comment]
Oh... Ok. Thanks for pointing that out.
I tried with the old viewer, and it's true that few 2048x2048 images can be projected. 
Most are way bigger than 256 MB (because many of those I found are 16-bit, which only allows 32 planes max).
Changing the "tiled images" threshold would, indeed, only affect small stacks.

**Comment by will-moore** [comment]
Actually, that cut-off itself is configurable on the server:
https://docs.openmicroscopy.org/omero/5.6.2/sysadmins/config.html#omero-pixeldata-max-projection-bytes
Although we need to update the iviewer and older viewer to also use that limit to enable/disable projections.
See https://github.com/ome/omero-web/issues/127 for older-viewer.
I'll keep this issue open for iviewer.
Apologies for missing that.
However, you should be aware that the server limit was introduced because larger images do take a lot of resources for projections (will be slow and cause issues).

Cheers,
  Will.

**Comment by ppouchin** [comment]
Ok! Thank you!
I may try to adjust this a bit then, but, just as you said, I understand that this would be heavier on the server (which is more "storage-oriented" than "computation-oriented").
