### ISSUE TITLE
512 timepoints takes long time to load settings

### ISSUE THREAD

**Issue by will-moore** [ome/omero-iviewer#371]
As reported by @sbesson on IDR, sample image with 512 timepoints takes 14 seconds to load the `Settings` right panel in iviewer.

**Comment by pwalczysko** [comment]
This issue should probably be "512 timepoints takes ...."

**Comment by sbesson** [comment]
I think there are two separate problems and I cannot remember which one this issue was trying to capture:

- we have numerous examples of images with >500 timepoints. We have seen an issue associated with the initial loading the plane metadata like the timestamps for large timelapse acquisition e.g. images with 100K timepoints like the primary data produced by super-resolution microscopy. I think this is what #373 aims at improving
- a separate issue was found when I tried to load an image which truly has 512 channels. In that case, the loading time was limited by the number of calls to the channel rendering settings server-side. This might be less relevant for our immediate use cases but for handling some hyperspectral modalities, I assume this is something that will need to be investigated.

**Comment by pwalczysko** [comment]
@sbesson thank you, do you please have a pointer to the primary data produced by super-resolution microscopy ? I tried and failed to find some myself (super-resulution is not listed as an imaging method in the OMERO.gallery )
